MD001: false # Heading increment (allow for template examples)
MD003: false # Heading style (allow setext in code examples)
MD013: false # Line length
MD024: false # Duplicate headings (allow for template examples with repeated sections)
MD025: false # Single H1 (allow for template examples)
MD026: false # Trailing punctuation in headings (allow colons for examples)
MD029: false # Ordered list prefix (allow non-sequential numbering)
MD032: false # Blanks around lists (allow for code examples)
MD033: false # Inline HTML
MD034: false # Bare URLs (allow for documentation links)
MD036: false # Emphasis as heading (allow for numbered items)
MD040: false # Fenced code language (allow unlabeled blocks)
MD041: false # First line heading
MD046: false # Code block style (allow indented in nested blocks)
MD060: false # Table column style (allow flexible table formatting)
