MD013: false # Line length
MD026: false # Trailing punctuation in headings (allow colons for examples)
MD029: false # Ordered list prefix (allow non-sequential numbering)
MD033: false # Inline HTML
MD034: false # Bare URLs (allow for documentation links)
MD036: false # Emphasis as heading (allow for numbered items)
MD040: false # Fenced code language (allow unlabeled blocks)
MD041: false # First line heading
MD060: false # Table column style (allow flexible table formatting)
