const args = Bun.argv.slice(2);

const HELP = `
setup-scaffold — Generate a bootstrap script from detected toolchain requirements

Usage:
  bun run tools/setup-scaffold.ts [project-dir] [options]

Options:
  --output <file>   Write script to file (default: stdout)
  --json            Output as JSON instead of shell script
  --help            Show this help message

Reads project configuration to detect required tools and generates a shell script
that installs everything needed for local development. The generated script should
be reviewed before running.
`.trim();

if (args.includes("--help")) {
  console.log(HELP);
  process.exit(0);
}

const jsonOutput = args.includes("--json");
const outputIdx = args.indexOf("--output");
const outputFile = outputIdx !== -1 ? args[outputIdx + 1] : null;
const filteredArgs = args.filter(
  (a, i) => !a.startsWith("--") && (outputIdx === -1 || i !== outputIdx + 1)
);
const projectDir = filteredArgs[0] || ".";

interface SetupStep {
  name: string;
  check: string;
  install: string;
  required: boolean;
}

async function main() {
  const { resolve, join } = await import("node:path");
  const { existsSync } = await import("node:fs");

  const dir = resolve(projectDir);
  const steps: SetupStep[] = [];

  // Read project config
  const pkgPath = join(dir, "package.json");
  let pkg: Record<string, any> = {};
  if (existsSync(pkgPath)) {
    pkg = JSON.parse(await Bun.file(pkgPath).text());
  }

  const hasBunLock = existsSync(join(dir, "bun.lockb")) || existsSync(join(dir, "bun.lock"));
  const hasNpmLock = existsSync(join(dir, "package-lock.json"));
  const hasDockerCompose =
    existsSync(join(dir, "docker-compose.yml")) ||
    existsSync(join(dir, "docker-compose.yaml")) ||
    existsSync(join(dir, "compose.yaml")) ||
    existsSync(join(dir, "compose.yml"));
  const hasDockerfile = existsSync(join(dir, "Dockerfile"));
  const hasToolVersions = existsSync(join(dir, ".tool-versions"));

  // Homebrew (macOS)
  steps.push({
    name: "Homebrew",
    check: "command -v brew",
    install: '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"',
    required: true,
  });

  // Git
  steps.push({
    name: "Git",
    check: "command -v git",
    install: "brew install git",
    required: true,
  });

  // mise (for .tool-versions)
  if (hasToolVersions) {
    steps.push({
      name: "mise",
      check: "command -v mise",
      install: "brew install mise",
      required: true,
    });
  }

  // Bun
  if (hasBunLock) {
    const requiredVersion = pkg.engines?.bun || "latest";
    steps.push({
      name: "Bun",
      check: "command -v bun",
      install: "curl -fsSL https://bun.sh/install | bash",
      required: true,
    });
  }

  // Node (for non-Bun projects)
  if (hasNpmLock && !hasBunLock) {
    steps.push({
      name: "Node.js",
      check: "command -v node",
      install: "brew install node",
      required: true,
    });
  }

  // Docker
  if (hasDockerCompose || hasDockerfile) {
    steps.push({
      name: "OrbStack (Docker)",
      check: "command -v docker",
      install: "brew install orbstack",
      required: true,
    });
  }

  // Generate script
  const scriptLines: string[] = [];
  scriptLines.push("#!/bin/bash");
  scriptLines.push("set -euo pipefail");
  scriptLines.push("");
  scriptLines.push(`# Bootstrap script for ${pkg.name || "this project"}`);
  scriptLines.push(`# Generated by setup-scaffold — review before running`);
  scriptLines.push("");

  scriptLines.push('GREEN="\\033[0;32m"');
  scriptLines.push('RED="\\033[0;31m"');
  scriptLines.push('NC="\\033[0m"');
  scriptLines.push("");

  scriptLines.push("check() {");
  scriptLines.push('  if eval "$1" &>/dev/null; then');
  scriptLines.push('    echo -e "${GREEN}[OK]${NC} $2"');
  scriptLines.push("    return 0");
  scriptLines.push("  else");
  scriptLines.push('    echo -e "${RED}[MISSING]${NC} $2"');
  scriptLines.push("    return 1");
  scriptLines.push("  fi");
  scriptLines.push("}");
  scriptLines.push("");

  scriptLines.push('echo "Checking prerequisites..."');
  scriptLines.push("");

  for (const step of steps) {
    scriptLines.push(`# ${step.name}`);
    scriptLines.push(`if ! check "${step.check}" "${step.name}"; then`);
    scriptLines.push(`  echo "Installing ${step.name}..."`);
    scriptLines.push(`  ${step.install}`);
    scriptLines.push("fi");
    scriptLines.push("");
  }

  // Tool versions
  if (hasToolVersions) {
    scriptLines.push("# Install tool versions from .tool-versions");
    scriptLines.push("mise install");
    scriptLines.push("");
  }

  // Dependencies
  if (hasBunLock) {
    scriptLines.push("# Install project dependencies");
    scriptLines.push("bun install");
    scriptLines.push("");
  } else if (hasNpmLock) {
    scriptLines.push("# Install project dependencies");
    scriptLines.push("npm ci");
    scriptLines.push("");
  }

  // Docker services
  if (hasDockerCompose) {
    scriptLines.push("# Start Docker services");
    scriptLines.push("docker compose up -d");
    scriptLines.push("");
  }

  scriptLines.push('echo ""');
  scriptLines.push('echo -e "${GREEN}Setup complete!${NC}"');

  const script = scriptLines.join("\n");

  if (jsonOutput) {
    console.log(JSON.stringify({ steps, script }, null, 2));
  } else if (outputFile) {
    const { resolve: resolvePath } = await import("node:path");
    await Bun.write(resolvePath(outputFile), script);
    const { chmodSync } = await import("node:fs");
    chmodSync(resolvePath(outputFile), 0o755);
    console.log(`Bootstrap script written to ${outputFile}`);
    console.log("Review the script, then run: bash " + outputFile);
  } else {
    console.log(script);
  }
}

main().catch((err) => {
  console.error(`Error: ${err.message}`);
  process.exit(1);
});
